### ISSUE TITLE
Descriptions of output files

### ISSUE THREAD

**Issue by WFRCAnalytics** [WFRCAnalytics/utah_bike_demand_model#3]
Can we get some quick basic metadata/descriptions on what each output csv is? @bstabler @blakerosenthal . Apologies if this is already documented somewhere

**Comment by blakerosenthal** [comment]
I've updated the README in the micromobility repo to better describe the output files! Let me know if anything needs further elaboration.

https://github.com/RSGInc/micromobility_toolset/blob/master/README.md
