### ISSUE TITLE
Reroute output csvs to different folder than inputs

### ISSUE THREAD

**Issue by WFRCAnalytics** [WFRCAnalytics/utah_bike_demand_model#4]
@joshua-reynolds  can check into this, should be too hard

**Comment by blakerosenthal** [comment]
The micromobility package could also be updated to write the `assign_demand` results to a different folder. Only the trip files need to be written to the original data folder, since they are also used as inputs for some steps.

**Comment by joshua-reynolds** [comment]
Thanks Blake
