### ISSUE TITLE
At-grade crossing attribute on Trails dataset

### ISSUE THREAD

**Issue by joshua-reynolds** [WFRCAnalytics/utah_bike_demand_model#6]
Need a way to identify off-street paths that do not have at-grade crossings (where bridges or tunnels mean no delay/stress at road crossings) so they can be excluded from intersection and signal delay calculations. 

Example - Parleys trail from Wasatch Blvd to 1700 S. 

Sounds like you already have a way to do this, but I thought it would be cool to track any input data tasks we do for this project

**Comment by nicolewfrc** [comment]
Grade separated crossings have been identified in Utrans Trails and Pathways dataset with Cartocode = 8 and Class = Grade Separated Crossing.  There may be some stray ones I missed but I think I got most of the crossings, especially on the regional routes.
